# Generated by Django 5.0.6 on 2026-06-29 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Nova conversa', max_length=200)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Conversa de IA',
                'verbose_name_plural': 'Conversas de IA',
                'ordering': ['-criada_em'],
            },
        ),
        migrations.CreateModel(
            name='AIMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('system', 'Sistema'), ('user', 'Eu'), ('assistant', 'Assistente')], max_length=20)),
                ('conteudo', models.TextField()),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('conversa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai_app.aiconversation')),
            ],
            options={
                'verbose_name': 'Mensagem de IA',
                'verbose_name_plural': 'Mensagens de IA',
                'ordering': ['criada_em'],
            },
        ),
    ]
