# Generated by Django 5.0.6 on 2026-06-29 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Novo banco', max_length=200)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('pagina', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='database', to='documents.page')),
            ],
            options={
                'verbose_name': 'Banco de Dados',
                'verbose_name_plural': 'Bancos de Dados',
            },
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('kind', models.CharField(choices=[('text', 'Texto'), ('number', 'Número'), ('date', 'Data'), ('select', 'Seleção Simples'), ('multiselect', 'Seleção Múltipla'), ('checkbox', 'Caixa de Seleção'), ('url', 'URL'), ('email', 'E-mail'), ('formula', 'Fórmula'), ('relation', 'Relação'), ('rollup', 'Rollup')], default='text', max_length=20)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('database', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='grids.database')),
            ],
            options={
                'verbose_name': 'Campo',
                'verbose_name_plural': 'Campos',
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('excluido_em', models.DateTimeField(blank=True, null=True)),
                ('database', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='grids.database')),
            ],
            options={
                'verbose_name': 'Registro',
                'verbose_name_plural': 'Registros',
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='View',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Visualização', max_length=200)),
                ('kind', models.CharField(choices=[('grid', 'Grade'), ('board', 'Quadro'), ('calendar', 'Calendário')], default='grid', max_length=20)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('database', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='grids.database')),
            ],
            options={
                'verbose_name': 'Visualização',
                'verbose_name_plural': 'Visualizações',
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CellValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.JSONField(blank=True, default=dict)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='grids.field')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='grids.record')),
            ],
            options={
                'verbose_name': 'Valor de Célula',
                'verbose_name_plural': 'Valores de Célula',
                'unique_together': {('record', 'field')},
            },
        ),
    ]
