# Generated by Django 5.0.6 on 2026-07-14 04:49
"""
Migration: add unique_together(database, nome) on Field.
Includes a data-migration step to deduplicate fields by name within each database
before applying the constraint, to avoid IntegrityError.
"""

from django.db import migrations, models


def deduplicate_fields(apps, schema_editor):
    """Remove duplicate Field entries sharing the same (database_id, nome).
    
    For each group of duplicates:
      - Keep the field with the lowest id.
      - Re-point any CellValue rows referencing a removed field to the kept field.
      - Delete the duplicate Field rows.
    """
    Field = apps.get_model("grids", "Field")
    CellValue = apps.get_model("grids", "CellValue")
    db_alias = schema_editor.connection.alias

    # 1) Find all (database_id, nome) pairs that appear more than once
    all_fields = Field.objects.using(db_alias).all().order_by("id")
    seen: dict[tuple[int, str], list[int]] = {}  # (db_id, nome) -> [field_ids]
    for f in all_fields:
        key = (f.database_id, f.nome)
        seen.setdefault(key, []).append(f.id)

    dupes = {k: v for k, v in seen.items() if len(v) > 1}
    if not dupes:
        return  # no duplicates — nothing to clean up

    total_removed = 0
    for (db_id, nome), ids in dupes.items():
        keep_id = ids[0]          # smallest id is first (ordered by id ASC)
        remove_ids = ids[1:]      # everything after the first is a duplicate

        # 2) Re-point cells that reference a duplicate field to the kept field
        for dup_id in remove_ids:
            CellValue.objects.using(db_alias).filter(field_id=dup_id).update(field_id=keep_id)

        # 3) Delete duplicate Field rows
        deleted, _ = Field.objects.using(db_alias).filter(id__in=remove_ids).delete()
        total_removed += deleted

    if total_removed:
        print(f"  → Deduplication complete: {total_removed} duplicate field(s) removed.")


class Migration(migrations.Migration):

    dependencies = [
        ("grids", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(deduplicate_fields, reverse_code=migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name="field",
            unique_together={("database", "nome")},
        ),
    ]
