# Generated by Django 5.0.6 on 2026-06-29 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(choices=[('light', 'Claro'), ('dark', 'Escuro'), ('system', 'Sistema')], default='system', max_length=10, verbose_name='Tema')),
                ('idioma', models.CharField(default='pt-br', max_length=10)),
            ],
            options={
                'verbose_name': 'Preferência',
                'verbose_name_plural': 'Preferências',
            },
        ),
    ]
